### ISSUE TITLE
Cucumber tests parallel execution with Testlab

### ISSUE THREAD

**Issue by anas-baadshah** [cucumber/cucumber-android#59]
Problem: 
I am running Cucumber UI tests with Firebase Testlab. All are working fine. The sequential run is successful and getting all reports.
Currently, I am trying to distribute the tests to run it on Testlab parallelly But seems like it is failing to find the tests. 
I am getting some log which says 0 test cases found
```
0 test / 1 shard
1 matrix ids created in 0m 10s
```

It is actually run all the cases sequentially on the 1 shard created. But no parallel runs.
My Gcloud configuration looks like this
```
gcloud:
  # test and app are the only required args
  app: .apkpath
  test: .testapkPath
  auto-google-login: false
  use-orchestrator: true
  instrumentation: true
  environment-variables:
    coverage: true
    coverageFilePath: /sdcard/
    clearPackageData: true
  directories-to-pull:
    - /sdcard/
  performance-metrics: false
  num-flaky-test-attempts: 0
  device:
    - model: "NexusLowRes"
      version: 29

  results-bucket: bucket_name
  results-dir: results
  locale: en
  test-runner-class: CucumberInstrumentationRunner
  record-video: true
  timeout: 30m
  num-uniform-shards: 8 //Not working
```

Cucumber configuration:
```
@CucumberOptions(
        features = "features",
        glue = "com.test",
        tags = {"@mySevenTests"},
        monochrome = true)
```

```
class Hooks {
    @Rule
    var activityTestRule = ActivityTestRule(
            InitialActivity::class.java,
            shouldLaunchActivity = true,
            isInitialTouchMode = true)
            .with(MockWebServerExecutorTestTask())

    private var activity: Activity? = null

    @Before("@mySevenTests")
    fun setup(scenario: Scenario) {
            activityTestRule.launchActivity(null)
            activity = activityTestRule.activity
        }

    @After("@mySevenTests")
    fun tearDown(){
        activity?.finish()
    }
}
```
**Cucumber Android version `4.8.4`**

Can someone please help on this.
